import { RESTAURANT_IMAGES } from '../assets/images/images'

export const DINING_HISTORY = [
  {
    id: 1,
    date: 'September 30, 2024',
    restaurant: 'Chinos',
    event: "Steven's Birthday",
    primaryDiner: '@joejoe',
  },
  {
    id: 12,
    date: 'September 30, 2024',
    restaurant: 'Chinos',
    event: "Steven's Birthday",
    primaryDiner: '@joejoe',
  },
  {
    id: 14,
    date: 'September 30, 2024',
    restaurant: 'Chinos',
    event: "Steven's Birthday",
    primaryDiner: '@joejoe',
  },
  {
    id: 16,
    date: 'September 30, 2024',
    restaurant: 'Chinos',
    event: "Steven's Birthday",
    primaryDiner: '@joejoe',
  },
  {
    id: 21,
    date: 'September 30, 2024',
    restaurant: 'Chinos',
    event: "Steven's Birthday",
    primaryDiner: '@joejoe',
  },
  {
    id: 91,
    date: 'September 30, 2024',
    restaurant: 'Chinos',
    event: "Steven's Birthday",
    primaryDiner: '@joejoe',
  },
]

export const DINER_DATA = [
  {
    id: 1,
    name: 'Theo Breaux',
    username: '@theobreaux',
    location: 'Los Angeles, CA',
  },
  {
    id: 2,
    name: 'Payton Tyrell',
    username: '@paytontyrell',
    location: 'Los Angeles, CA',
  },
  {
    id: 3,
    name: 'Payton Tyrell',
    username: '@paytontyrell',
    location: 'Los Angeles, CA',
  },
  {
    id: 4,
    name: 'Payton Tyrell',
    username: '@paytontyrell',
    location: 'Los Angeles, CA',
  },
  {
    id: 5,
    name: 'Payton Tyrell',
    username: '@paytontyrell',
    location: 'Los Angeles, CA',
  },
  {
    id: 6,
    name: 'Payton Tyrell',
    username: '@paytontyrell',
    location: 'Los Angeles, CA',
  },
  {
    id: 7,
    name: 'Payton Tyrell',
    username: '@paytontyrell',
    location: 'Los Angeles, CA',
  },
]

export const RESTAURANT_DATA = [
  {
    id: 1,
    restaurantName: 'Tasty',
    address: '7984 Santa Monica Blvd.',
    city: 'West Hollywoood',
    state: 'CA',
    zip: '90046',
    rating: '4.5',
    phone: '(323) 883-1805',
    cuisine: 'Thai',
    image: RESTAURANT_IMAGES.image1,
    website: 'https://www.tastynoodlehouse.us/',
  },
  {
    id: 2,
    restaurantName: 'Crossroads',
    address: '7984 Santa Monica Blvd.',
    city: 'West Hollywoood',
    state: 'CA',
    zip: '90046',
    rating: '4.5',
    phone: '(323) 883-1805',
    cuisine: 'Vegan',
    image: RESTAURANT_IMAGES.image1,
    website: 'https://www.tastynoodlehouse.us/',
  },
  {
    id: 3,
    restaurantName: 'Tasty',
    address: '7984 Santa Monica Blvd.',
    city: 'West Hollywoood',
    state: 'CA',
    zip: '90046',
    rating: '4.5',
    phone: '(323) 883-1805',
    cuisine: 'Vegan',
    image: RESTAURANT_IMAGES.image1,
    website: 'https://www.tastynoodlehouse.us/',
  },
  {
    id: 4,
    restaurantName: 'Tasty',
    address: '7984 Santa Monica Blvd.',
    city: 'West Hollywoood',
    state: 'CA',
    zip: '90046',
    rating: '4.5',
    phone: '(323) 883-1805',
    cuisine: 'Thai',
    image: RESTAURANT_IMAGES.image1,
    website: 'https://www.tastynoodlehouse.us/',
  },
  {
    id: 5,
    restaurantName: 'Tasty',
    address: '7984 Santa Monica Blvd.',
    city: 'West Hollywoood',
    state: 'CA',
    zip: '90046',
    rating: '4.5',
    phone: '(323) 883-1805',
    cuisine: 'Vegan',
    image: RESTAURANT_IMAGES.image1,
    website: 'https://www.tastynoodlehouse.us/',
  },
  {
    id: 6,
    restaurantName: 'Tasty',
    address: '7984 Santa Monica Blvd.',
    city: 'West Hollywoood',
    state: 'CA',
    zip: '90046',
    rating: '4.5',
    phone: '(323) 883-1805',
    cuisine: 'Vegan',
    image: RESTAURANT_IMAGES.image1,
    website: 'https://www.tastynoodlehouse.us/',
  },
  {
    id: 7,
    restaurantName: 'Tasty',
    address: '7984 Santa Monica Blvd.',
    city: 'West Hollywoood',
    state: 'CA',
    zip: '90046',
    rating: '4.5',
    phone: '(323) 883-1805',
    cuisine: 'Vegan',
    image: RESTAURANT_IMAGES.image1,
    website: 'https://www.tastynoodlehouse.us/',
  },
]
