import { RESTAURANT_IMAGES } from '../assets/images/images'

export const RESTAURANT_DATA = [
  {
    id: 1,
    restaurantName: 'Tasty',
    address: '7984 Santa Monica Blvd.',
    city: 'West Hollywoood',
    state: 'CA',
    zip: '90046',
    rating: '4.5',
    phone: '(323) 883-1805',
    cuisine: 'Thai',
    image: RESTAURANT_IMAGES.image1,
    website: 'www.theobreaux.com',
  },
  {
    id: 2,
    restaurantName: 'Crossroads',
    address: '7984 Santa Monica Blvd.',
    city: 'West Hollywoood',
    state: 'CA',
    zip: '90046',
    rating: '4.5',
    phone: '(323) 883-1805',
    cuisine: 'Vegan',
    image: RESTAURANT_IMAGES.image1,
    website: 'www.theobreaux.com',
  },
  {
    id: 3,
    restaurantName: 'Tasty',
    address: '7984 Santa Monica Blvd.',
    city: 'West Hollywoood',
    state: 'CA',
    zip: '90046',
    rating: '4.5',
    phone: '(323) 883-1805',
    cuisine: 'Vegan',
    image: RESTAURANT_IMAGES.image1,
    website: 'www.theobreaux.com',
  },
  {
    id: 4,
    restaurantName: 'Tasty',
    address: '7984 Santa Monica Blvd.',
    city: 'West Hollywoood',
    state: 'CA',
    zip: '90046',
    rating: '4.5',
    phone: '(323) 883-1805',
    cuisine: 'Thai',
    image: RESTAURANT_IMAGES.image1,
    website: 'www.theobreaux.com',
  },
  {
    id: 5,
    restaurantName: 'Tasty',
    address: '7984 Santa Monica Blvd.',
    city: 'West Hollywoood',
    state: 'CA',
    zip: '90046',
    rating: '4.5',
    phone: '(323) 883-1805',
    cuisine: 'Vegan',
    image: RESTAURANT_IMAGES.image1,
    website: 'www.theobreaux.com',
  },
  {
    id: 6,
    restaurantName: 'Tasty',
    address: '7984 Santa Monica Blvd.',
    city: 'West Hollywoood',
    state: 'CA',
    zip: '90046',
    rating: '4.5',
    phone: '(323) 883-1805',
    cuisine: 'Vegan',
    image: RESTAURANT_IMAGES.image1,
    website: 'www.theobreaux.com',
  },
  {
    id: 7,
    restaurantName: 'Tasty',
    address: '7984 Santa Monica Blvd.',
    city: 'West Hollywoood',
    state: 'CA',
    zip: '90046',
    rating: '4.5',
    phone: '(323) 883-1805',
    cuisine: 'Vegan',
    image: RESTAURANT_IMAGES.image1,
    website: 'www.theobreaux.com',
  },
]
