import { RESTAURANT_IMAGES } from '../assets/images/images'

export const RESTAURANT_DATA = [
  {
    id: 1,
    restaurantName: 'Tasty',
    address: '7984 Santa Monica Blvd.',
    city: 'West Hollywoood',
    state: 'CA',
    zip: '90046',
    rating: '4.5',
    image: RESTAURANT_IMAGES.image1,
  },
  {
    id: 2,
    restaurantName: 'Tasty',
    address: '7984 Santa Monica Blvd.',
    city: 'West Hollywoood',
    state: 'CA',
    zip: '90046',
    rating: '4.5',
    image: RESTAURANT_IMAGES.image1,
  },
  {
    id: 3,
    restaurantName: 'Tasty',
    address: '7984 Santa Monica Blvd.',
    city: 'West Hollywoood',
    state: 'CA',
    zip: '90046',
    rating: '4.5',
    image: RESTAURANT_IMAGES.image1,
  },
  {
    id: 4,
    restaurantName: 'Tasty',
    address: '7984 Santa Monica Blvd.',
    city: 'West Hollywoood',
    state: 'CA',
    zip: '90046',
    rating: '4.5',
    image: RESTAURANT_IMAGES.image1,
  },
  {
    id: 5,
    restaurantName: 'Tasty',
    address: '7984 Santa Monica Blvd.',
    city: 'West Hollywoood',
    state: 'CA',
    zip: '90046',
    rating: '4.5',
    image: RESTAURANT_IMAGES.image1,
  },
]
