export const FETCH_FEATURED_RESTAURANTS = 'FETCH_FEATURED_RESTAURANTS'
export const FETCH_FEATURED_RESTAURANTS_SUCCESS = 'FETCH_FEATURED_RESTAURANTS_SUCCESS'
export const FETCH_FEATURED_RESTAURANTS_FAILURE = 'FETCH_FEATURED_RESTAURANTS_FAILURE'

export const SET_CURRENT_CITY = 'SET_CURRENT_CITY'

export const SET_LOCAL_RESTAURANTS = 'SET_LOCAL_RESTAURANTS'
export const SET_LOCAL_RESTAURANTS_SUCCESS = 'SET_LOCAL_RESTAURANTS_SUCCESS'
export const SET_LOCAL_RESTAURANTS_FAILURE = 'SET_LOCAL_RESTAURANTS_FAILURE'

export const SET_USER = 'SET_USER'
