export const AUTO_COMPLETE_DINER = 'AUTO_COMPLETE_DINER'
export const AUTO_COMPLETE_DINER_FAILURE = 'AUTO_COMPLETE_DINER_FAILURE'
export const AUTO_COMPLETE_DINER_SUCCESS = 'AUTO_COMPLETE_DINER_SUCCESS'

export const FETCH_DINING_HISTORY = 'FETCH_DINING_HISTORY'
export const FETCH_DINING_HISTORY_FAILURE = 'FETCH_DINING_HISTORY_FAILURE'
export const FETCH_DINING_HISTORY_SUCCESS = 'FETCH_DINING_HISTORY_SUCCESS'

export const FETCH_FEATURED_RESTAURANTS = 'FETCH_FEATURED_RESTAURANTS'
export const FETCH_FEATURED_RESTAURANTS_FAILURE = 'FETCH_FEATURED_RESTAURANTS_FAILURE'
export const FETCH_FEATURED_RESTAURANTS_SUCCESS = 'FETCH_FEATURED_RESTAURANTS_SUCCESS'

export const POST_DINING_EVENT = 'POST_DINING_EVENT'
export const POST_DINING_EVENT_FAILURE = 'POST_DINING_EVENT_FAILURE'
export const POST_DINING_EVENT_SUCCESS = 'POST_DINING_EVENT_SUCCESS'

export const SET_CURRENT_CITY_SUCCESS = 'SET_CURRENT_CITY_SUCCESS'

export const SET_LOCAL_RESTAURANTS = 'SET_LOCAL_RESTAURANTS'
export const SET_LOCAL_RESTAURANTS_FAILURE = 'SET_LOCAL_RESTAURANTS_FAILURE'
export const SET_LOCAL_RESTAURANTS_SUCCESS = 'SET_LOCAL_RESTAURANTS_SUCCESS'

export const SET_RECEIPT_DATA_FAILURE = 'SET_RECEIPT_DATA_FAILURE'
export const SET_RECEIPT_DATA_SUCCESS = 'SET_RECEIPT_DATA_SUCCESS'

export const SET_USER_SUCCESS = 'SET_USER_SUCCESS'
