export const FETCH_FEATURED_RESTAURANTS = 'FETCH_FEATURED_RESTAURANTS'
export const FETCH_FEATURED_RESTAURANTS_SUCCESS = 'FETCH_FEATURED_RESTAURANTS_SUCCESS'
export const FETCH_FEATURED_RESTAURANTS_FAILURE = 'FETCH_FEATURED_RESTAURANTS_FAILURE'
export const SET_USER = 'SET_USER'
